---
- hosts: asl-ridgeback
  remote_user: asl-admin
  tasks:
    - name: Add apt repository
      become: yes
      apt_repository:
        repo: deb http://packages.ros.org/ros/ubuntu bionic main
        state: present
    - name: Add key to keyserver
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        state: present
    - name: Update package lists
      become: yes
      apt:
        update_cache: true
    - name: Install ros.
      become: yes
      apt:
        name: ros-melodic-ros-base
        state: present
    - name: Rosdep update
      become: yes
      shell: |
        rosdep init
        rosdep update
    - name: Source ros in bashrc
      lineinfile: dest=~/.bashrc regexp="^source \/opt\/ros\/melodic\/setup.bash" line="source /opt/ros/melodic/setup.bash"
    - name: Install required packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python-rosinstall
          - python-rosinstall-generator
          - python-wstool
          - build-essential
          - python-catkin-tools
